function random() { x = Math.random();
			return x; 
    }


function randomQuestion() {
    
    var questionArray = ['Adding one bit ____ the amount of information that can be represented.', 'A(n) ____ is the set of rules governing the exchange or transmission of data between devices.', 'The ____ created the first multi-computer network known as the ARPANET.', 'What does HTTP stand for?', 'ASCII is used to ______', 'A high-quality internet connection has______.','What program is used to access websites?','A .Com domain is typically used for a _____ site.','A ____ connects to the host server.','Images in the ____ domain are not protected by copyright.','How do you start an HTML document?','What are some editors you can use to make HTML, CSS, etc? (Multiple Answers)','Which one of these fonts is not installed by default?','Which tag is used before an individual item in lists?','How do you link an external JavaScript page?','What tag shows a table row?','How do you correctly call an image in HTML?','How do you add a horizontal rule?','Which heading tag is the largest?','Which ways can you call a color in HTML?','Which one of these properties is used to change the text color in CSS?','Which property below increases space inside an element in CSS?','How do you correctly add multiple margins in one line of code if the top margin is 100px, the right margin is 150px, the bottom margin is 100px, and the left margin is 80px in CSS?','Which symbol is used to call an id in CSS?','What is the outermost element found in the box model?','How do you add a border to an element with only one line of code in CSS?','How do you use a font that has multiple words in CSS?','What should you add to the <a> tag if you want to change the color of a previously visited link in CSS?','How do you add a background color to an element in CSS?','How do you align text in CSS?','How do you write a message to the console in JavaScript?','How do you comment a single line in JavaScript?','Which answer below maintains proper Camelcase?','What is a string used for?','What is used to alter HTML with Javascript?','How do you create an array in JavaScript?','JavaScript was originally called _____.','How do you write an alert to the user in JavaScript?','How do you make an if statement?','How do you create a function?','Easter Egg',];
var rand = questionArray[Math.floor(x * questionArray.length)];
document.getElementById("Question").innerHTML = rand;
    
}

function randomAnswerA() {
    var answerArrayA = ['Doubles', 'Domain', 'Government', 'Hyperlink to Text Protocol', 'Encode text in an easy to understand format', 'High Bandwidth; Low Latency', 'Internet Browser', 'Commercial', 'Client', 'Public', '<html>', 'Android Studio', 'Times New Roman', '<ol>', 'myFunction()=embed', '<tablerow>', '<img src=”dankmemes.jpg”>', '<horizontalrule>', '<h3>', 'color=”#FFFFFF”', 'h1 {color:red;}', 'h1 padding:5px, p {margin: 100px 150px 100px 80px;}', '%', 'Padding', 'border-left: red solid 6px;', 'font-family: |Comic Sans MS|;', 'a:hover', 'background-color: white;', 'gravity: falls;',];
var rand = answerArrayA[Math.floor(x * answerArrayA.length)];
document.getElementById("a").innerHTML = rand;
    
}
function randomAnswerB() {
    var answerArrayB = ['Triples', 'Protocol', 'Harvard College', 'Hypertext Transfer Protocol', 'Encrypt Passwords', 'A high-quality internet connection has______.','What program is used to access websites?','A .Com domain is typically used for a _____ site.','A ____ connects to the host server.','Images in the ____ domain are not protected by copyright.','How do you start an HTML document?','What are some editors you can use to make HTML, CSS, etc? (Multiple Answers)','Which one of these fonts is not installed by default?','Which tag is used before an individual item in lists?','How do you link an external JavaScript page?','What tag shows a table row?','How do you correctly call an image in HTML?','How do you add a horizontal rule?','Which heading tag is the largest?','Which ways can you call a color in HTML?','Which one of these properties is used to change the text color in CSS?','Which property below increases space inside an element in CSS?','How do you correctly add multiple margins in one line of code if the top margin is 100px, the right margin is 150px, the bottom margin is 100px, and the left margin is 80px in CSS?','Which symbol is used to call an id in CSS?','What is the outermost element found in the box model?','How do you add a border to an element with only one line of code in CSS?','How do you use a font that has multiple words in CSS?','What should you add to the “a” if you want to change the color of a previously visited link in CSS?','How do you add a background color to an element in CSS?','How do you align text in CSS?','How do you write a message to the console in JavaScript?','How do you comment a single line in JavaScript?','Which answer below maintains proper Camelcase?','What is a string used for?','What is used to alter HTML with Javascript?','How do you create an array in JavaScript?','JavaScript was originally called _____.','How do you write an alert to the user in JavaScript?','How do you make an if statement?','How do you create a function?','Easter Egg',];
var rand = answerArrayB[Math.floor(x * answerArrayB.length)];
document.getElementById("b").innerHTML = rand;
    
}
function randomAnswerC() {
    var answerArrayC = ['Halves', 'A(n) ____ is the set of rules governing the exchange or transmission of data between devices.', 'The ____ created the first multi-computer network known as the ARPANET.', 'What does HTTP stand for?', 'ASCII is used to ______', 'A high-quality internet connection has______.','What program is used to access websites?','A .Com domain is typically used for a _____ site.','A ____ connects to the host server.','Images in the ____ domain are not protected by copyright.','How do you start an HTML document?','What are some editors you can use to make HTML, CSS, etc? (Multiple Answers)','Which one of these fonts is not installed by default?','Which tag is used before an individual item in lists?','How do you link an external JavaScript page?','What tag shows a table row?','How do you correctly call an image in HTML?','How do you add a horizontal rule?','Which heading tag is the largest?','Which ways can you call a color in HTML?','Which one of these properties is used to change the text color in CSS?','Which property below increases space inside an element in CSS?','How do you correctly add multiple margins in one line of code if the top margin is 100px, the right margin is 150px, the bottom margin is 100px, and the left margin is 80px in CSS?','Which symbol is used to call an id in CSS?','What is the outermost element found in the box model?','How do you add a border to an element with only one line of code in CSS?','How do you use a font that has multiple words in CSS?','What should you add to the “a” if you want to change the color of a previously visited link in CSS?','How do you add a background color to an element in CSS?','How do you align text in CSS?','How do you write a message to the console in JavaScript?','How do you comment a single line in JavaScript?','Which answer below maintains proper Camelcase?','What is a string used for?','What is used to alter HTML with Javascript?','How do you create an array in JavaScript?','JavaScript was originally called _____.','How do you write an alert to the user in JavaScript?','How do you make an if statement?','How do you create a function?','Easter Egg',];
var rand = answerArrayC[Math.floor(x * answerArrayC.length)];
document.getElementById("c").innerHTML = rand;
    
}
function randomAnswerD() {
    var answerArrayD = ['Does Nothing', 'A(n) ____ is the set of rules governing the exchange or transmission of data between devices.', 'The ____ created the first multi-computer network known as the ARPANET.', 'What does HTTP stand for?', 'ASCII is used to ______', 'A high-quality internet connection has______.','What program is used to access websites?','A .Com domain is typically used for a _____ site.','A ____ connects to the host server.','Images in the ____ domain are not protected by copyright.','How do you start an HTML document?','What are some editors you can use to make HTML, CSS, etc? (Multiple Answers)','Which one of these fonts is not installed by default?','Which tag is used before an individual item in lists?','How do you link an external JavaScript page?','What tag shows a table row?','How do you correctly call an image in HTML?','How do you add a horizontal rule?','Which heading tag is the largest?','Which ways can you call a color in HTML?','Which one of these properties is used to change the text color in CSS?','Which property below increases space inside an element in CSS?','How do you correctly add multiple margins in one line of code if the top margin is 100px, the right margin is 150px, the bottom margin is 100px, and the left margin is 80px in CSS?','Which symbol is used to call an id in CSS?','What is the outermost element found in the box model?','How do you add a border to an element with only one line of code in CSS?','How do you use a font that has multiple words in CSS?','What should you add to the <a> tag if you want to change the color of a previously visited link in CSS?','How do you add a background color to an element in CSS?','How do you align text in CSS?','How do you write a message to the console in JavaScript?','How do you comment a single line in JavaScript?','Which answer below maintains proper Camelcase?','What is a string used for?','What is used to alter HTML with Javascript?','How do you create an array in JavaScript?','JavaScript was originally called _____.','How do you write an alert to the user in JavaScript?','How do you make an if statement?','How do you create a function?','Easter Egg',];
var rand = answerArrayD[Math.floor(x * answerArrayD.length)];
document.getElementById("d").innerHTML = rand;
    
} 


// Colors For Incorrect and Correct Answers 

function correctAnswer() {
    document.getElementById("body").style.color = "green";
}

function wrongAnswer() {
    document.getElementById("body").style.color = "red";
}